# Generated by Django 5.1.6 on 2025-02-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
